spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/featherweight?currentSchema=public
    username: norpac 
    password: password

cognito:
  region: us-west-2 
  pool-id: us-west-2_O5NAjDcDT

